/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.vcita.platform.client.JSON;

/**
 * The deep link to an inner product page. This is not made for third-party apps, but for apps that open as part of the product. Made for internal developer use only.
 */
@ApiModel(description = "The deep link to an inner product page. This is not made for third-party apps, but for apps that open as part of the product. Made for internal developer use only.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AppsDeepLink {
  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_PATH_PARAMS = "path_params";
  @SerializedName(SERIALIZED_NAME_PATH_PARAMS)
  private Object pathParams;

  public AppsDeepLink() { 
  }

  public AppsDeepLink path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * The relative path to the page.
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The relative path to the page.")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  public AppsDeepLink pathParams(Object pathParams) {
    
    this.pathParams = pathParams;
    return this;
  }

   /**
   * The params that will be added to the path URL (optional)
   * @return pathParams
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The params that will be added to the path URL (optional)")

  public Object getPathParams() {
    return pathParams;
  }


  public void setPathParams(Object pathParams) {
    this.pathParams = pathParams;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppsDeepLink appsDeepLink = (AppsDeepLink) o;
    return Objects.equals(this.path, appsDeepLink.path) &&
        Objects.equals(this.pathParams, appsDeepLink.pathParams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, pathParams);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppsDeepLink {\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    pathParams: ").append(toIndentedString(pathParams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("path");
    openapiFields.add("path_params");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AppsDeepLink
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (AppsDeepLink.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has reuqired fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in AppsDeepLink is not found in the empty JSON string", AppsDeepLink.openapiRequiredFields.toString()));
        }
      }
      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AppsDeepLink.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AppsDeepLink` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AppsDeepLink.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AppsDeepLink' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AppsDeepLink> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AppsDeepLink.class));

       return (TypeAdapter<T>) new TypeAdapter<AppsDeepLink>() {
           @Override
           public void write(JsonWriter out, AppsDeepLink value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AppsDeepLink read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AppsDeepLink given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AppsDeepLink
  * @throws IOException if the JSON string is invalid with respect to AppsDeepLink
  */
  public static AppsDeepLink fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AppsDeepLink.class);
  }

 /**
  * Convert an instance of AppsDeepLink to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

