/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vcita.platform.client.model.ClientPackage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.vcita.platform.client.JSON;

/**
 * Data21
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Data21 {
  public static final String SERIALIZED_NAME_CLIENT_PACKAGES = "client_packages";
  @SerializedName(SERIALIZED_NAME_CLIENT_PACKAGES)
  private List<ClientPackage> clientPackages = null;

  public Data21() { 
  }

  public Data21 clientPackages(List<ClientPackage> clientPackages) {
    
    this.clientPackages = clientPackages;
    return this;
  }

  public Data21 addClientPackagesItem(ClientPackage clientPackagesItem) {
    if (this.clientPackages == null) {
      this.clientPackages = new ArrayList<>();
    }
    this.clientPackages.add(clientPackagesItem);
    return this;
  }

   /**
   * Get clientPackages
   * @return clientPackages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ClientPackage> getClientPackages() {
    return clientPackages;
  }


  public void setClientPackages(List<ClientPackage> clientPackages) {
    this.clientPackages = clientPackages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data21 data21 = (Data21) o;
    return Objects.equals(this.clientPackages, data21.clientPackages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientPackages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data21 {\n");
    sb.append("    clientPackages: ").append(toIndentedString(clientPackages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("client_packages");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Data21
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (Data21.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has reuqired fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in Data21 is not found in the empty JSON string", Data21.openapiRequiredFields.toString()));
        }
      }
      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Data21.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Data21` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      JsonArray jsonArrayclientPackages = jsonObj.getAsJsonArray("client_packages");
      // validate the optional field `client_packages` (array)
      if (jsonArrayclientPackages != null) {
        for (int i = 0; i < jsonArrayclientPackages.size(); i++) {
          ClientPackage.validateJsonObject(jsonArrayclientPackages.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Data21.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Data21' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Data21> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Data21.class));

       return (TypeAdapter<T>) new TypeAdapter<Data21>() {
           @Override
           public void write(JsonWriter out, Data21 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Data21 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Data21 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Data21
  * @throws IOException if the JSON string is invalid with respect to Data21
  */
  public static Data21 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Data21.class);
  }

 /**
  * Convert an instance of Data21 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

