/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vcita.platform.client.model.Item1;
import com.vcita.platform.client.model.Product;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import com.vcita.platform.client.JSON;

/**
 * Datum15
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Datum15 {
  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DISCOUNT_AMOUNT = "discount_amount";
  @SerializedName(SERIALIZED_NAME_DISCOUNT_AMOUNT)
  private Integer discountAmount;

  public static final String SERIALIZED_NAME_DISCOUNT_UNIT = "discount_unit";
  @SerializedName(SERIALIZED_NAME_DISCOUNT_UNIT)
  private String discountUnit;

  public static final String SERIALIZED_NAME_EXPIRATION = "expiration";
  @SerializedName(SERIALIZED_NAME_EXPIRATION)
  private Integer expiration;

  public static final String SERIALIZED_NAME_EXPIRATION_UNIT = "expiration_unit";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_UNIT)
  private String expirationUnit;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_IMAGE_PATH = "image_path";
  @SerializedName(SERIALIZED_NAME_IMAGE_PATH)
  private Object imagePath = null;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<Item1> items = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ONLINE_PAYMENT_ENABLED = "online_payment_enabled";
  @SerializedName(SERIALIZED_NAME_ONLINE_PAYMENT_ENABLED)
  private Boolean onlinePaymentEnabled;

  public static final String SERIALIZED_NAME_ORIGINAL_PRICE = "original_price";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_PRICE)
  private String originalPrice;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private String price;

  public static final String SERIALIZED_NAME_PRODUCTS = "products";
  @SerializedName(SERIALIZED_NAME_PRODUCTS)
  private List<Product> products = null;

  public static final String SERIALIZED_NAME_TOTAL_BOOKINGS = "total_bookings";
  @SerializedName(SERIALIZED_NAME_TOTAL_BOOKINGS)
  private Integer totalBookings;

  public Datum15() { 
  }

  public Datum15 active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  public Datum15 currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public Datum15 description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public Datum15 discountAmount(Integer discountAmount) {
    
    this.discountAmount = discountAmount;
    return this;
  }

   /**
   * Get discountAmount
   * @return discountAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDiscountAmount() {
    return discountAmount;
  }


  public void setDiscountAmount(Integer discountAmount) {
    this.discountAmount = discountAmount;
  }


  public Datum15 discountUnit(String discountUnit) {
    
    this.discountUnit = discountUnit;
    return this;
  }

   /**
   * Get discountUnit
   * @return discountUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDiscountUnit() {
    return discountUnit;
  }


  public void setDiscountUnit(String discountUnit) {
    this.discountUnit = discountUnit;
  }


  public Datum15 expiration(Integer expiration) {
    
    this.expiration = expiration;
    return this;
  }

   /**
   * Get expiration
   * @return expiration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getExpiration() {
    return expiration;
  }


  public void setExpiration(Integer expiration) {
    this.expiration = expiration;
  }


  public Datum15 expirationUnit(String expirationUnit) {
    
    this.expirationUnit = expirationUnit;
    return this;
  }

   /**
   * Get expirationUnit
   * @return expirationUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getExpirationUnit() {
    return expirationUnit;
  }


  public void setExpirationUnit(String expirationUnit) {
    this.expirationUnit = expirationUnit;
  }


  public Datum15 id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Datum15 imagePath(Object imagePath) {
    
    this.imagePath = imagePath;
    return this;
  }

   /**
   * Get imagePath
   * @return imagePath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getImagePath() {
    return imagePath;
  }


  public void setImagePath(Object imagePath) {
    this.imagePath = imagePath;
  }


  public Datum15 items(List<Item1> items) {
    
    this.items = items;
    return this;
  }

  public Datum15 addItemsItem(Item1 itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Item1> getItems() {
    return items;
  }


  public void setItems(List<Item1> items) {
    this.items = items;
  }


  public Datum15 name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Datum15 onlinePaymentEnabled(Boolean onlinePaymentEnabled) {
    
    this.onlinePaymentEnabled = onlinePaymentEnabled;
    return this;
  }

   /**
   * Get onlinePaymentEnabled
   * @return onlinePaymentEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getOnlinePaymentEnabled() {
    return onlinePaymentEnabled;
  }


  public void setOnlinePaymentEnabled(Boolean onlinePaymentEnabled) {
    this.onlinePaymentEnabled = onlinePaymentEnabled;
  }


  public Datum15 originalPrice(String originalPrice) {
    
    this.originalPrice = originalPrice;
    return this;
  }

   /**
   * Get originalPrice
   * @return originalPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOriginalPrice() {
    return originalPrice;
  }


  public void setOriginalPrice(String originalPrice) {
    this.originalPrice = originalPrice;
  }


  public Datum15 price(String price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPrice() {
    return price;
  }


  public void setPrice(String price) {
    this.price = price;
  }


  public Datum15 products(List<Product> products) {
    
    this.products = products;
    return this;
  }

  public Datum15 addProductsItem(Product productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Product> getProducts() {
    return products;
  }


  public void setProducts(List<Product> products) {
    this.products = products;
  }


  public Datum15 totalBookings(Integer totalBookings) {
    
    this.totalBookings = totalBookings;
    return this;
  }

   /**
   * Get totalBookings
   * @return totalBookings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalBookings() {
    return totalBookings;
  }


  public void setTotalBookings(Integer totalBookings) {
    this.totalBookings = totalBookings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Datum15 datum15 = (Datum15) o;
    return Objects.equals(this.active, datum15.active) &&
        Objects.equals(this.currency, datum15.currency) &&
        Objects.equals(this.description, datum15.description) &&
        Objects.equals(this.discountAmount, datum15.discountAmount) &&
        Objects.equals(this.discountUnit, datum15.discountUnit) &&
        Objects.equals(this.expiration, datum15.expiration) &&
        Objects.equals(this.expirationUnit, datum15.expirationUnit) &&
        Objects.equals(this.id, datum15.id) &&
        Objects.equals(this.imagePath, datum15.imagePath) &&
        Objects.equals(this.items, datum15.items) &&
        Objects.equals(this.name, datum15.name) &&
        Objects.equals(this.onlinePaymentEnabled, datum15.onlinePaymentEnabled) &&
        Objects.equals(this.originalPrice, datum15.originalPrice) &&
        Objects.equals(this.price, datum15.price) &&
        Objects.equals(this.products, datum15.products) &&
        Objects.equals(this.totalBookings, datum15.totalBookings);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, currency, description, discountAmount, discountUnit, expiration, expirationUnit, id, imagePath, items, name, onlinePaymentEnabled, originalPrice, price, products, totalBookings);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Datum15 {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    discountAmount: ").append(toIndentedString(discountAmount)).append("\n");
    sb.append("    discountUnit: ").append(toIndentedString(discountUnit)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    expirationUnit: ").append(toIndentedString(expirationUnit)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imagePath: ").append(toIndentedString(imagePath)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    onlinePaymentEnabled: ").append(toIndentedString(onlinePaymentEnabled)).append("\n");
    sb.append("    originalPrice: ").append(toIndentedString(originalPrice)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    totalBookings: ").append(toIndentedString(totalBookings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("active");
    openapiFields.add("currency");
    openapiFields.add("description");
    openapiFields.add("discount_amount");
    openapiFields.add("discount_unit");
    openapiFields.add("expiration");
    openapiFields.add("expiration_unit");
    openapiFields.add("id");
    openapiFields.add("image_path");
    openapiFields.add("items");
    openapiFields.add("name");
    openapiFields.add("online_payment_enabled");
    openapiFields.add("original_price");
    openapiFields.add("price");
    openapiFields.add("products");
    openapiFields.add("total_bookings");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Datum15
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (Datum15.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in Datum15 is not found in the empty JSON string", Datum15.openapiRequiredFields.toString()));
        }
      }
      Set<java.util.Map.Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (java.util.Map.Entry<String, JsonElement> entry : entries) {
        if (!Datum15.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Datum15` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      JsonArray jsonArrayitems = jsonObj.getAsJsonArray("items");
      // validate the optional field `items` (array)
      if (jsonArrayitems != null) {
        for (int i = 0; i < jsonArrayitems.size(); i++) {
          Item1.validateJsonObject(jsonArrayitems.get(i).getAsJsonObject());
        };
      }
      JsonArray jsonArrayproducts = jsonObj.getAsJsonArray("products");
      // validate the optional field `products` (array)
      if (jsonArrayproducts != null) {
        for (int i = 0; i < jsonArrayproducts.size(); i++) {
          Product.validateJsonObject(jsonArrayproducts.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Datum15.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Datum15' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Datum15> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Datum15.class));

       return (TypeAdapter<T>) new TypeAdapter<Datum15>() {
           @Override
           public void write(JsonWriter out, Datum15 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Datum15 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Datum15 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Datum15
  * @throws IOException if the JSON string is invalid with respect to Datum15
  */
  public static Datum15 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Datum15.class);
  }

 /**
  * Convert an instance of Datum15 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

