/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vcita.platform.client.model.CreditItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BookingCredit
 */
public class BookingCreditTest {
    private final BookingCredit model = new BookingCredit();

    /**
     * Model tests for BookingCredit
     */
    @Test
    public void testBookingCredit() {
        // TODO: test BookingCredit
    }

    /**
     * Test the property 'bookingsUsage'
     */
    @Test
    public void bookingsUsageTest() {
        // TODO: test bookingsUsage
    }

    /**
     * Test the property 'creditItems'
     */
    @Test
    public void creditItemsTest() {
        // TODO: test creditItems
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'totalBookings'
     */
    @Test
    public void totalBookingsTest() {
        // TODO: test totalBookings
    }

}
