/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BusinessesBusinessIdBusinessIntegrationsPlugins
 */
public class BusinessesBusinessIdBusinessIntegrationsPluginsTest {
    private final BusinessesBusinessIdBusinessIntegrationsPlugins model = new BusinessesBusinessIdBusinessIntegrationsPlugins();

    /**
     * Model tests for BusinessesBusinessIdBusinessIntegrationsPlugins
     */
    @Test
    public void testBusinessesBusinessIdBusinessIntegrationsPlugins() {
        // TODO: test BusinessesBusinessIdBusinessIntegrationsPlugins
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'planName'
     */
    @Test
    public void planNameTest() {
        // TODO: test planName
    }

    /**
     * Test the property 'siteUrl'
     */
    @Test
    public void siteUrlTest() {
        // TODO: test siteUrl
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
