/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vcita.platform.client.model.Data9;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BusinessesBusinessIdWizardsWizardNameGet200Response
 */
public class BusinessesBusinessIdWizardsWizardNameGet200ResponseTest {
    private final BusinessesBusinessIdWizardsWizardNameGet200Response model = new BusinessesBusinessIdWizardsWizardNameGet200Response();

    /**
     * Model tests for BusinessesBusinessIdWizardsWizardNameGet200Response
     */
    @Test
    public void testBusinessesBusinessIdWizardsWizardNameGet200Response() {
        // TODO: test BusinessesBusinessIdWizardsWizardNameGet200Response
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

}
