/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vcita.platform.client.model.BusinessesBusinessIdBusinessMetaPlan;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BusinessesBusinessIdBusinessMeta
 */
public class BusinessesBusinessIdBusinessMetaTest {
    private final BusinessesBusinessIdBusinessMeta model = new BusinessesBusinessIdBusinessMeta();

    /**
     * Model tests for BusinessesBusinessIdBusinessMeta
     */
    @Test
    public void testBusinessesBusinessIdBusinessMeta() {
        // TODO: test BusinessesBusinessIdBusinessMeta
    }

    /**
     * Test the property 'plan'
     */
    @Test
    public void planTest() {
        // TODO: test plan
    }

}
