/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vcita.platform.client.model.ActionData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Datum6
 */
public class Datum6Test {
    private final Datum6 model = new Datum6();

    /**
     * Model tests for Datum6
     */
    @Test
    public void testDatum6() {
        // TODO: test Datum6
    }

    /**
     * Test the property 'actedCount'
     */
    @Test
    public void actedCountTest() {
        // TODO: test actedCount
    }

    /**
     * Test the property 'actionData'
     */
    @Test
    public void actionDataTest() {
        // TODO: test actionData
    }

    /**
     * Test the property 'addedCount'
     */
    @Test
    public void addedCountTest() {
        // TODO: test addedCount
    }

    /**
     * Test the property 'backgroundColor'
     */
    @Test
    public void backgroundColorTest() {
        // TODO: test backgroundColor
    }

    /**
     * Test the property 'body'
     */
    @Test
    public void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'bouncedCount'
     */
    @Test
    public void bouncedCountTest() {
        // TODO: test bouncedCount
    }

    /**
     * Test the property 'businessUid'
     */
    @Test
    public void businessUidTest() {
        // TODO: test businessUid
    }

    /**
     * Test the property 'buttonBackgroundColor'
     */
    @Test
    public void buttonBackgroundColorTest() {
        // TODO: test buttonBackgroundColor
    }

    /**
     * Test the property 'buttonText'
     */
    @Test
    public void buttonTextTest() {
        // TODO: test buttonText
    }

    /**
     * Test the property 'buttonTextColor'
     */
    @Test
    public void buttonTextColorTest() {
        // TODO: test buttonTextColor
    }

    /**
     * Test the property 'clickCount'
     */
    @Test
    public void clickCountTest() {
        // TODO: test clickCount
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'deliverCount'
     */
    @Test
    public void deliverCountTest() {
        // TODO: test deliverCount
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'lastScheduledAt'
     */
    @Test
    public void lastScheduledAtTest() {
        // TODO: test lastScheduledAt
    }

    /**
     * Test the property 'lastSentAt'
     */
    @Test
    public void lastSentAtTest() {
        // TODO: test lastSentAt
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'readOnly'
     */
    @Test
    public void readOnlyTest() {
        // TODO: test readOnly
    }

    /**
     * Test the property 'smsContent'
     */
    @Test
    public void smsContentTest() {
        // TODO: test smsContent
    }

    /**
     * Test the property 'spamCount'
     */
    @Test
    public void spamCountTest() {
        // TODO: test spamCount
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'uid'
     */
    @Test
    public void uidTest() {
        // TODO: test uid
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'viewCount'
     */
    @Test
    public void viewCountTest() {
        // TODO: test viewCount
    }

}
