/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InlineObject29
 */
public class InlineObject29Test {
    private final InlineObject29 model = new InlineObject29();

    /**
     * Model tests for InlineObject29
     */
    @Test
    public void testInlineObject29() {
        // TODO: test InlineObject29
    }

    /**
     * Test the property 'businessUid'
     */
    @Test
    public void businessUidTest() {
        // TODO: test businessUid
    }

    /**
     * Test the property 'clientUid'
     */
    @Test
    public void clientUidTest() {
        // TODO: test clientUid
    }

    /**
     * Test the property 'eventInstanceUid'
     */
    @Test
    public void eventInstanceUidTest() {
        // TODO: test eventInstanceUid
    }

    /**
     * Test the property 'matterUid'
     */
    @Test
    public void matterUidTest() {
        // TODO: test matterUid
    }

}
