/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vcita.platform.client.model.Branding;
import com.vcita.platform.client.model.Plan;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Meta
 */
public class MetaTest {
    private final Meta model = new Meta();

    /**
     * Model tests for Meta
     */
    @Test
    public void testMeta() {
        // TODO: test Meta
    }

    /**
     * Test the property 'authToken'
     */
    @Test
    public void authTokenTest() {
        // TODO: test authToken
    }

    /**
     * Test the property 'branding'
     */
    @Test
    public void brandingTest() {
        // TODO: test branding
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'identities'
     */
    @Test
    public void identitiesTest() {
        // TODO: test identities
    }

    /**
     * Test the property 'inSetup'
     */
    @Test
    public void inSetupTest() {
        // TODO: test inSetup
    }

    /**
     * Test the property 'intents'
     */
    @Test
    public void intentsTest() {
        // TODO: test intents
    }

    /**
     * Test the property 'isTemplate'
     */
    @Test
    public void isTemplateTest() {
        // TODO: test isTemplate
    }

    /**
     * Test the property 'marketingChannel'
     */
    @Test
    public void marketingChannelTest() {
        // TODO: test marketingChannel
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'plan'
     */
    @Test
    public void planTest() {
        // TODO: test plan
    }

    /**
     * Test the property 'suggestedIdentities'
     */
    @Test
    public void suggestedIdentitiesTest() {
        // TODO: test suggestedIdentities
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
