/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentCheckoutCardCardInfo
 */
public class PaymentCheckoutCardCardInfoTest {
    private final PaymentCheckoutCardCardInfo model = new PaymentCheckoutCardCardInfo();

    /**
     * Model tests for PaymentCheckoutCardCardInfo
     */
    @Test
    public void testPaymentCheckoutCardCardInfo() {
        // TODO: test PaymentCheckoutCardCardInfo
    }

    /**
     * Test the property 'cardBrand'
     */
    @Test
    public void cardBrandTest() {
        // TODO: test cardBrand
    }

    /**
     * Test the property 'cardholderName'
     */
    @Test
    public void cardholderNameTest() {
        // TODO: test cardholderName
    }

    /**
     * Test the property 'expMonth'
     */
    @Test
    public void expMonthTest() {
        // TODO: test expMonth
    }

    /**
     * Test the property 'expYear'
     */
    @Test
    public void expYearTest() {
        // TODO: test expYear
    }

    /**
     * Test the property 'last4'
     */
    @Test
    public void last4Test() {
        // TODO: test last4
    }

}
