/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Plan
 */
public class PlanTest {
    private final Plan model = new Plan();

    /**
     * Model tests for Plan
     */
    @Test
    public void testPlan() {
        // TODO: test Plan
    }

    /**
     * Test the property 'expiresOn'
     */
    @Test
    public void expiresOnTest() {
        // TODO: test expiresOn
    }

    /**
     * Test the property 'externalSubscriptionParams'
     */
    @Test
    public void externalSubscriptionParamsTest() {
        // TODO: test externalSubscriptionParams
    }

    /**
     * Test the property 'planName'
     */
    @Test
    public void planNameTest() {
        // TODO: test planName
    }

    /**
     * Test the property 'staffSlots'
     */
    @Test
    public void staffSlotsTest() {
        // TODO: test staffSlots
    }

}
