/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.api;

import com.vcita.platform.client.ApiException;
import com.vcita.platform.client.model.GlobalEventAttendancesGet200Response;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EventAttendanceApi
 */
@Ignore
public class EventAttendanceApiTest {

    private final EventAttendanceApi api = new EventAttendanceApi();

    
    /**
     * Gets a list of event attendances
     *
     * Gets a list of event attendances
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void globalEventAttendancesGetTest() throws ApiException {
        String date = null;
        String authorization = null;
        Integer page = null;
                GlobalEventAttendancesGet200Response response = api.globalEventAttendancesGet(date, authorization, page);
        // TODO: test validations
    }
    
}
