/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.api;

import com.vcita.platform.client.ApiException;
import com.vcita.platform.client.model.InlineObject15;
import com.vcita.platform.client.model.LeadgenPost201Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LeadGenApi
 */
@Disabled
public class LeadGenApiTest {

    private final LeadGenApi api = new LeadGenApi();

    /**
     * Creates a lead
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void leadgenPostTest() throws ApiException {
        String authorization = null;
        String xOnBehalfOf = null;
        InlineObject15 inlineObject15 = null;
        LeadgenPost201Response response = api.leadgenPost(authorization, xOnBehalfOf, inlineObject15);
        // TODO: test validations
    }

}
