/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.api;

import com.vcita.platform.client.ApiException;
import com.vcita.platform.client.model.InlineObject18;
import com.vcita.platform.client.model.PaymentCheckoutPut201Response;
import com.vcita.platform.client.model.PaymentCheckoutUrlKeyGet201Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentCheckoutApi
 */
@Disabled
public class PaymentCheckoutApiTest {

    private final PaymentCheckoutApi api = new PaymentCheckoutApi();

    /**
     * Send checkout update by webhook 
     *
     * Update a checkout process from webhook
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void paymentCheckoutPutTest() throws ApiException {
        String authorization = null;
        InlineObject18 inlineObject18 = null;
        PaymentCheckoutPut201Response response = api.paymentCheckoutPut(authorization, inlineObject18);
        // TODO: test validations
    }

    /**
     * Get Open Checkout For Specific url_key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void paymentCheckoutUrlKeyGetTest() throws ApiException {
        String authorization = null;
        String urlKey = null;
        PaymentCheckoutUrlKeyGet201Response response = api.paymentCheckoutUrlKeyGet(authorization, urlKey);
        // TODO: test validations
    }

}
