/*
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.platform.client.api;

import com.vcita.platform.client.ApiException;
import com.vcita.platform.client.model.SchedulingSchedulingFormsGetFormGet200Response;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SchedulingFormsApi
 */
@Ignore
public class SchedulingFormsApiTest {

    private final SchedulingFormsApi api = new SchedulingFormsApi();


    /**
     *
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void schedulingSchedulingFormsGetFormGetTest() throws ApiException {
        String businessId = null;
        String serviceId = null;
        String sourceName = null;
                SchedulingSchedulingFormsGetFormGet200Response response = api.schedulingSchedulingFormsGetFormGet(businessId, serviceId, sourceName);
        // TODO: test validations
    }

}
